<?php
require_once '../config/config.php';
require_once '../includes/functions.php';
if (!isLoggedIn() || !hasRole('employee')) redirect('../login.php');

$db = getDBConnection();
$currentUser = getCurrentUser();

// Get user's tasks
$stmt = $db->prepare("
    SELECT t.*, p.project_name FROM tasks t
    JOIN projects p ON t.project_id = p.id
    WHERE t.assigned_to = ? AND t.status != 'completed'
    ORDER BY t.due_date ASC
");
$stmt->execute([$currentUser['id']]);
$tasks = $stmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Time Boxing - <?php echo SITE_NAME; ?></title>
    <link rel="stylesheet" href="../assets/css/vien-v3.css">

    <!-- Synto Dashboard Template Design -->
    <link rel="stylesheet" href="../assets/css/synto-design.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        .time-grid {
            display: grid;
            grid-template-columns: 80px 1fr;
            gap: 0;
            background: var(--bg-primary);
            border-radius: 8px;
            overflow: hidden;
        }
        .time-label {
            padding: 10px;
            border-bottom: 1px solid var(--border-color);
            background: var(--bg-secondary);
            font-size: 12px;
            text-align: center;
        }
        .time-slot {
            padding: 10px;
            border-bottom: 1px solid var(--border-color);
            min-height: 60px;
            position: relative;
            cursor: pointer;
            transition: background 0.2s;
        }
        .time-slot:hover {
            background: var(--bg-secondary);
        }
        .time-box {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 8px;
            border-radius: 4px;
            margin: 2px 0;
            font-size: 13px;
            cursor: pointer;
            transition: transform 0.2s;
        }
        .time-box:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
        }
        .time-box-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 4px;
        }
        .time-box-task {
            font-size: 11px;
            opacity: 0.9;
        }
        .date-selector {
            display: flex;
            align-items: center;
            gap: 15px;
            margin-bottom: 20px;
        }
        .date-nav {
            display: flex;
            gap: 10px;
        }
    </style>
</head>
<body>
    <div class="app-container">
        <?php include '../includes/v3-employee-sidebar.php'; ?>
        <div class="main-content">
            <?php include '../includes/v3-header.php'; ?>
            <div class="content-wrapper">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;">
                    <h1><i class="fas ri-calendar-line-check"></i> Time Boxing</h1>
                    <button onclick="showAddBoxModal()" class="btn btn-primary">
                        <i class="fas ri-add-line"></i> Add Time Block
                    </button>
                </div>

                <div class="date-selector">
                    <div class="date-nav">
                        <button onclick="changeDate(-1)" class="btn" style="padding:8px 12px;">
                            <i class="fas fa-chevron-left"></i>
                        </button>
                        <button onclick="changeDate(1)" class="btn" style="padding:8px 12px;">
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>
                    <input type="date" id="selectedDate" class="form-control" style="width:auto;" onchange="loadTimeBoxes()" value="<?php echo date('Y-m-d'); ?>">
                    <button onclick="goToToday()" class="btn">Today</button>
                </div>

                <div class="dashboard-card">
                    <div class="card-body" style="padding:0;">
                        <div class="time-grid" id="timeGrid">
                            <!-- Time slots will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add Time Box Modal -->
    <div id="addBoxModal" class="modal">
        <div class="modal-content" style="max-width:500px;">
            <div class="modal-header">
                <h3>Add Time Block</h3>
                <button class="modal-close" onclick="closeAddBoxModal()">&times;</button>
            </div>
            <div class="modal-body">
                <label>Task (Optional)</label>
                <select id="boxTaskId" class="form-control">
                    <option value="">No specific task</option>
                    <?php foreach ($tasks as $task): ?>
                    <option value="<?php echo $task['id']; ?>"><?php echo e($task['task_name']); ?> - <?php echo e($task['project_name']); ?></option>
                    <?php endforeach; ?>
                </select>

                <label style="margin-top:15px;">Description</label>
                <input type="text" id="boxDescription" class="form-control" placeholder="What will you work on?">

                <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:15px;">
                    <div>
                        <label>Start Time</label>
                        <input type="time" id="boxStartTime" class="form-control">
                    </div>
                    <div>
                        <label>End Time</label>
                        <input type="time" id="boxEndTime" class="form-control">
                    </div>
                </div>

                <button onclick="saveTimeBox()" class="btn btn-primary" style="width:100%;margin-top:20px;">
                    <i class="fas fa-save"></i> Save Time Block
                </button>
            </div>
        </div>
    </div>

    <script>
        let currentBoxes = [];

        // Generate time grid (6 AM to 10 PM)
        function generateTimeGrid() {
            const grid = document.getElementById('timeGrid');
            grid.innerHTML = '';

            for (let hour = 6; hour <= 22; hour++) {
                const timeLabel = document.createElement('div');
                timeLabel.className = 'time-label';
                timeLabel.textContent = `${hour % 12 || 12}${hour >= 12 ? 'PM' : 'AM'}`;

                const timeSlot = document.createElement('div');
                timeSlot.className = 'time-slot';
                timeSlot.dataset.hour = hour;
                timeSlot.onclick = () => quickAddBox(hour);

                grid.appendChild(timeLabel);
                grid.appendChild(timeSlot);
            }
        }

        function quickAddBox(hour) {
            document.getElementById('boxStartTime').value = `${hour.toString().padStart(2, '0')}:00`;
            document.getElementById('boxEndTime').value = `${(hour + 1).toString().padStart(2, '0')}:00`;
            showAddBoxModal();
        }

        function loadTimeBoxes() {
            const date = document.getElementById('selectedDate').value;

            fetch('../api/productivity.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ action: 'get_time_boxes', date: date })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    currentBoxes = data.boxes;
                    renderTimeBoxes();
                }
            });
        }

        function renderTimeBoxes() {
            // Clear all slots
            document.querySelectorAll('.time-slot').forEach(slot => {
                slot.innerHTML = '';
            });

            // Place boxes in appropriate slots
            currentBoxes.forEach(box => {
                const startHour = parseInt(box.start_time.split(':')[0]);
                const endHour = parseInt(box.end_time.split(':')[0]);
                const slot = document.querySelector(`.time-slot[data-hour="${startHour}"]`);

                if (slot) {
                    const boxEl = document.createElement('div');
                    boxEl.className = 'time-box';
                    boxEl.innerHTML = `
                        <div class="time-box-header">
                            <span><i class="fas ri-time-line"></i> ${box.start_time} - ${box.end_time}</span>
                            <i class="fas fa-times" onclick="deleteTimeBox(${box.id}, event)" style="cursor:pointer;"></i>
                        </div>
                        <div><strong>${box.description || 'Work block'}</strong></div>
                        ${box.task_name ? `<div class="time-box-task">${box.task_name}</div>` : ''}
                    `;
                    slot.appendChild(boxEl);
                }
            });
        }

        function showAddBoxModal() {
            document.getElementById('addBoxModal').classList.add('active');
        }

        function closeAddBoxModal() {
            document.getElementById('addBoxModal').classList.remove('active');
            document.getElementById('boxTaskId').value = '';
            document.getElementById('boxDescription').value = '';
            document.getElementById('boxStartTime').value = '';
            document.getElementById('boxEndTime').value = '';
        }

        function saveTimeBox() {
            const taskId = document.getElementById('boxTaskId').value || null;
            const description = document.getElementById('boxDescription').value;
            const startTime = document.getElementById('boxStartTime').value;
            const endTime = document.getElementById('boxEndTime').value;
            const boxDate = document.getElementById('selectedDate').value;

            if (!startTime || !endTime) {
                alert('Please select start and end times');
                return;
            }

            fetch('../api/productivity.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'add_time_box',
                    task_id: taskId,
                    start_time: startTime,
                    end_time: endTime,
                    description: description,
                    box_date: boxDate
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    closeAddBoxModal();
                    loadTimeBoxes();
                } else {
                    alert('Error: ' + data.message);
                }
            });
        }

        function deleteTimeBox(boxId, event) {
            event.stopPropagation();
            if (!confirm('Delete this time block?')) return;

            fetch('../api/productivity.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'delete_time_box',
                    box_id: boxId
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    loadTimeBoxes();
                }
            });
        }

        function changeDate(days) {
            const dateInput = document.getElementById('selectedDate');
            const currentDate = new Date(dateInput.value);
            currentDate.setDate(currentDate.getDate() + days);
            dateInput.value = currentDate.toISOString().split('T')[0];
            loadTimeBoxes();
        }

        function goToToday() {
            document.getElementById('selectedDate').value = new Date().toISOString().split('T')[0];
            loadTimeBoxes();
        }

        // Initialize
        generateTimeGrid();
        loadTimeBoxes();
    </script>
    <script src="../assets/js/theme.js"></script>

    <!-- Synto Dashboard Interactions -->
    <script src="../assets/js/synto-interactions.js"></script>
</body>
</html>
